trigger:
  - master

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  image-name: humberd/notes-app-web
  image-tag: $(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: 'DockerHub - Humberd'

  - task: Bash@3
    displayName: Build and Push Manifest
    inputs:
      targetType: 'inline'
      script: |
        docker version
        docker buildx create
        docker buildx build -f .\docker\web-app\Dockerfile -t $(image-name):$(image-tag) -t $(image-name):latest --platform linux/amd64,linux/arm/v7 --push .

      failOnStderr: true

  - task: Docker@2
    displayName: Logout
    condition: always()
    inputs:
      command: logout
      containerRegistry: 'DockerHub - Humberd'
