// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY GENERATED BY extract-translation-types.js

export type TranslationKey =
    'core.app_title' |
    'core.bar' |
    'common.all_notes' |
    'common.starred' |
    'common.trash' |
    'common.tag' |
    'common.tags' |
    'common.new' |
    'common.search' |
    'common.delete' |
    'common.delete_permanently' |
    'common.restore' |
    'common.duplicate' |
    'common.star' |
    'common.unstar' |
    'common.edit' |
    'common.cancel' |
    'common.save' |
    'common.preview' |
    'common.name' |
    'common.raw' |
    'common.split' |
    'common.title' |
    'common.hide' |
    'common.show' |
    'tags.no_tags' |
    'tags.add_tag' |
    'tags.edit_tag' |
    'tags.edit_color' |
    'tags.delete_tag_dialog_title' |
    'tags.delete_tag_dialog_content' |
    'notes.title_placeholder' |
    'validators.color_hex';
